# User.create(first_name:"muse",last_name:"m",username: 'muse',password:'hey' )
# Topic.create(topic_title:"lakers", logo:"https://images.homedepot-static.com/productImages/1c4d5cb9-15b3-4e0c-a03e-3b6e6e12fde7/svn/los-angeles-lakers-logo-purple-trademark-kitchen-dining-tables-nba2000-lal-c3_1000.jpg", google_news:true, user_id: 1)
# PostTopic.create(post_id: 1, topic_id:1)
# Post.create(caption:"lakers sign new person")
# Favorite.create(post_id: 1, user_id:1)